setwd("C:/Users/18904/Github/complex-analysis/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
if(!file.exists("data/exponential_mapping.RData")){
  x=seq(-2,2,length.out=100)
  y=seq(0,2*pi,length.out=100)
  grid_x=outer(x,rep(1,length(y)))
  grid_y=outer(rep(1,length(x)),y)
  z=complex(re=as.vector(grid_x),im=as.vector(grid_y))
  w=exp(z)
  image_x=matrix(Re(w),nrow=length(x),ncol=length(y))
  image_y=matrix(Im(w),nrow=length(x),ncol=length(y))
  save(x,y,grid_x,grid_y,image_x,image_y,file="data/exponential_mapping.RData")
}
load("data/exponential_mapping.RData")
pdf("../figures/exponential_mapping.pdf",width=8,height=4)
par(mfrow=c(1,2),mar=c(4,4,3,1))
plot(NULL,xlim=c(-2.5,2.5),ylim=c(-0.5,2*pi+0.5),main="Original Rectangle",xlab="x",ylab="y",asp=1)
for(i in 1:length(x))lines(grid_x[i,],grid_y[i,],lty=1)
for(j in 1:length(y))lines(grid_x[,j],grid_y[,j],lty=2)
plot(NULL,xlim=c(-8,8),ylim=c(-8,8),main="Image After w=e^z",xlab="u",ylab="v",asp=1)
for(i in 1:length(x))lines(image_x[i,],image_y[i,],lty=1)
for(j in 1:length(y))lines(image_x[,j],image_y[,j],lty=2)
dev.off()
