setwd("C:/Users/18904/Github/complex-analysis/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
if(!file.exists("data/jordan_curve_theorem.RData")){
  theta=seq(0,2*pi,length.out=100)
  r=1+0.3*sin(3*theta)
  curve_x=r*cos(theta)
  curve_y=r*sin(theta)
  inside_x=seq(-0.5,0.5,length.out=10)
  inside_y=seq(-0.5,0.5,length.out=10)
  outside_x=seq(-2,2,length.out=10)
  outside_y=seq(-2,2,length.out=10)
  save(theta,curve_x,curve_y,inside_x,inside_y,outside_x,outside_y,file="data/jordan_curve_theorem.RData")
}
load("data/jordan_curve_theorem.RData")
pdf("../figures/jordan_curve_theorem.pdf",width=4,height=4)
par(mfrow=c(1,1),mar=c(4,4,3,1))
plot(NULL,xlim=c(-2,2),ylim=c(-2,2),main="Jordan Curve Theorem",xlab="x",ylab="y",asp=1)
lines(curve_x,curve_y,lty=1,lwd=2)
points(0,0,pch=19)
text(0,0,"  interior",pos=3)
points(1.5,1.5,pch=1)
text(1.5,1.5,"  exterior",pos=3)
dev.off()
