setwd("C:/Users/18904/Github/complex-analysis/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
if(!file.exists("data/mobius_transformation.RData")){
  theta=seq(0,2*pi,length.out=100)
  circle_x=0.5+cos(theta)
  circle_y=sin(theta)
  z=complex(re=circle_x,im=circle_y)
  w=1/z
  image_x=Re(w)
  image_y=Im(w)
  save(theta,circle_x,circle_y,image_x,image_y,file="data/mobius_transformation.RData")
}
load("data/mobius_transformation.RData")
pdf("../figures/mobius_transformation.pdf",width=8,height=4)
par(mfrow=c(1,2),mar=c(4,4,3,1))
plot(NULL,xlim=c(-2,2),ylim=c(-2,2),main="Original Circle",xlab="x",ylab="y",asp=1)
lines(circle_x,circle_y,lty=1)
points(0,0,pch=19)
text(0,0,"  origin",pos=3)
plot(NULL,xlim=c(-2,2),ylim=c(-2,2),main="Image After w=1/z",xlab="u",ylab="v",asp=1)
lines(image_x,image_y,lty=2)
points(0,0,pch=19)
text(0,0,"  origin",pos=3)
dev.off()
