setwd("C:/Users/18904/Github/complex-analysis/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
if(!file.exists("data/region_definition.RData")){
  theta=seq(0,2*pi,length.out=100)
  circle_x=cos(theta)
  circle_y=sin(theta)
  points_inside=cbind(0.5*cos(seq(0,2*pi,length.out=20)),0.5*sin(seq(0,2*pi,length.out=20)))
  boundary_points=cbind(cos(seq(0,2*pi,length.out=20)),sin(seq(0,2*pi,length.out=20)))
  path_x=c(-0.5,0,0.5,0.3,-0.2)
  path_y=c(-0.3,0.2,0.5,0.1,-0.4)
  save(theta,circle_x,circle_y,points_inside,boundary_points,path_x,path_y,file="data/region_definition.RData")
}
load("data/region_definition.RData")
pdf("../figures/region_definition.pdf",width=10,height=5)
par(mfrow=c(1,2),mar=c(4,4,3,1))
plot(NULL,xlim=c(-1.5,1.5),ylim=c(-1.5,1.5),main="Open Set",xlab="x",ylab="y",asp=1)
lines(circle_x,circle_y,lty=2)
points(points_inside,pch=19,col="black")
points(boundary_points,pch=1,lty=1)
text(0,0,"  interior\n points",pos=3)
text(1,1,"  boundary",pos=3)
plot(NULL,xlim=c(-1,1),ylim=c(-1,1),main="Path Connected",xlab="x",ylab="y",asp=1)
lines(circle_x,circle_y,lty=2)
points(path_x,path_y,type="l",lty=1,lwd=2)
points(path_x[1],path_y[1],pch=19)
points(path_x[length(path_x)],path_y[length(path_y)],pch=19)
text(path_x[1],path_y[1],"  a",pos=4)
text(path_x[length(path_x)],path_y[length(path_y)],"  b",pos=4)
dev.off()
