setwd("C:/Users/18904/Github/complex-analysis/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
if(!file.exists("data/riemann_mapping_theorem.RData")){
  theta=seq(0,2*pi,length.out=100)
  disk_x=cos(theta)
  disk_y=sin(theta)
  square_x=c(-1,-1,1,1,-1)
  square_y=c(-1,1,1,-1,-1)
  save(theta,disk_x,disk_y,square_x,square_y,file="data/riemann_mapping_theorem.RData")
}
load("data/riemann_mapping_theorem.RData")
pdf("../figures/riemann_mapping_theorem.pdf",width=8,height=4)
par(mfrow=c(1,2),mar=c(4,4,3,1))
plot(NULL,xlim=c(-1.5,1.5),ylim=c(-1.5,1.5),main="Simply Connected Domain",xlab="x",ylab="y",asp=1)
lines(square_x,square_y,lty=1)
text(0,0,"  D",pos=3)
plot(NULL,xlim=c(-1.5,1.5),ylim=c(-1.5,1.5),main="Unit Disk",xlab="u",ylab="v",asp=1)
lines(disk_x,disk_y,lty=1)
text(0,0,"  D",pos=3)
dev.off()
