setwd("C:/Users/18904/Github/complex-analysis/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
if(!file.exists("data/simply_vs_multiply_connected.RData")){
  theta=seq(0,2*pi,length.out=100)
  disk_x=cos(theta)
  disk_y=sin(theta)
  annulus_outer_x=1.5*cos(theta)
  annulus_outer_y=1.5*sin(theta)
  annulus_inner_x=0.5*cos(theta)
  annulus_inner_y=0.5*sin(theta)
  save(theta,disk_x,disk_y,annulus_outer_x,annulus_outer_y,annulus_inner_x,annulus_inner_y,file="data/simply_vs_multiply_connected.RData")
}
load("data/simply_vs_multiply_connected.RData")
pdf("../figures/simply_vs_multiply_connected.pdf",width=8,height=4)
par(mfrow=c(1,2),mar=c(4,4,3,1))
plot(NULL,xlim=c(-1.5,1.5),ylim=c(-1.5,1.5),main="Simply Connected",xlab="x",ylab="y",asp=1)
lines(disk_x,disk_y,lty=1)
text(0,0,"  no holes",pos=3)
plot(NULL,xlim=c(-2,2),ylim=c(-2,2),main="Multiply Connected",xlab="x",ylab="y",asp=1)
lines(annulus_outer_x,annulus_outer_y,lty=1)
lines(annulus_inner_x,annulus_inner_y,lty=2)
text(0,0,"  hole",pos=3)
dev.off()
